name: CD Github Actions
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Release version'
        required: true

jobs:
  Call-CI:
    uses: ./.github/workflows/ci.yml

  Deploy-DockerHub:
    needs: Call-CI
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            brunobotelhobr/my-ip-calculator
        # generate Docker tags for the images, altest and version
            tags: |
              latest
              ${{ github.event.inputs.version }}
           
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
