name: CD Github Actions
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Release version'
        required: true

jobs:
  Call-CI:
    uses: ./.github/workflows/ci.yml

  Deploy-DockerHub:
    needs: Call-CI
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 
            - "brunobotelhobr/my-ip-calulator:latest"
            - "brunobotelhobr/my-ip-calulator:${{ github.event.inputs.version }}"
